# Generated by Django 5.1.1 on 2024-10-08 00:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventario_inicial', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('llegada_mercancia', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('mercancia_defectuosa', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('mercancia_sobrante', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('producto', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
