# Generated by Django 5.1.1 on 2024-10-08 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        ('registros', '0002_registroventas_personal_registroventas_sucursal_and_more'),
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroventas',
            name='personal',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.personal'),
        ),
        migrations.AlterField(
            model_name='registroventas',
            name='sucursal',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucursales.sucursal'),
        ),
    ]
