# Generated by Django 5.1.1 on 2024-10-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_registroventas_personal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroventas',
            name='gastos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
