# Generated by Django 5.1.1 on 2024-10-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_registroventas_gastos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroventas',
            name='gastos',
        ),
    ]
