# Generated by Django 5.1.1 on 2024-10-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datos_transferencia', models.TextField()),
                ('turno', models.CharField(choices=[('S-D', 'Sab-dom'), ('L-V', 'Lun-viernes')], max_length=5)),
            ],
        ),
    ]
