# Generated by Django 5.1.1 on 2024-10-08 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registros', '0005_remove_registroventas_gastos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('registro_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_diarios', to='registros.registroventas')),
            ],
        ),
    ]
